spring.profiles.active=mongo

spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=biblioteca-dosw-eci-2024-clave-secreta-jwt
app.jwt.expiration-ms=86400000

spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.hyord2y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=DOSW-Library

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html